# Generated by Django 5.0.9 on 2024-09-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('TitleName', models.CharField(max_length=30)),
                ('HasPassport', models.BooleanField()),
                ('Salary', models.IntegerField()),
                ('BirthDate', models.DateField()),
                ('HireDate', models.DateField()),
                ('Notes', models.CharField(max_length=200)),
                ('Country', models.CharField(choices=[('PAK', 'PAKISTAN'), ('IND', 'INDIA'), ('USA', 'United States Of America'), ('AUS', 'AUSTRALIA'), ('AU', 'AUSTRIA'), ('UAE', 'United Arab Emirates')], default=None, max_length=35)),
            ],
        ),
    ]
