# Generated by Django 5.0.9 on 2024-09-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0007_alter_employee_empdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTimeEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('TitleName', models.CharField(max_length=30)),
            ],
        ),
    ]
