# Generated by Django 5.0.9 on 2024-09-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validationsdemoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='postal_code',
            field=models.IntegerField(verbose_name='Postal Code'),
        ),
    ]
